### ISSUE TITLE
Custom model culling issue

### ISSUE THREAD

**Issue by cosmodd** [sashakoshka/ccc#1]
Hello !

I was trying your resourcepack today and got into a culling issue with it:
![image](https://github.com/sashakoshka/ccc/assets/23277700/3087b884-777d-48cf-a28c-5fcccc8107d4)

Instance configuration: 
- **CC:Tweaked 1.19.2 1.101.3**
- **Forge 4.3.0**
- **ComputerCraft Create 2.0.0**

I don't know if it's possible to fix on the resource pack side since in your screenshots it seems to be fine.
Let me know !

**Comment by sashakoshka** [comment]
I had this issue as well when trying to create models for some peripherals hence why most of them are still full blocks. I did not have this issue with the computers themselves, which is probably because I'm using cc-restitched on fabric. I do want to figure out why this happens and fix it at some point but I'm afraid it may be caused by the mod itself. There is a similar issue being experienced with [cc-overhaul](https://github.com/cc-orgs/cc-overhaul) and they describe it as a bug with tweaked.

**Comment by cosmodd** [comment]
Thank you for the informations 👍 from what a friend has tested CC:T consider computers as full blocks so it will constantly cull "non-visible" faces. He even made a modified version of CC:T to change this and it worked so yeah 🤷

I'm closing the issue now since it's not fixable on the resource pack side.
Ty again and have a good day 👋

**Comment by sashakoshka** [comment]
I ended up removing the custom models for now
